language: node_js
cache: npm
script: npm test
before_install: git config --global url."https://".insteadOf ssh://
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $TRAVIS_BRANCH"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
    secure: a+rEmazVlncZl9gdGxCbdPP1rSvkur52UEhYeAMkPHXrvYh6++BcH0QOEZI2fWf5d1krcBABi3TCBgY0fiOVhB9IYBOYi0AO2oNFs0ItfWR5aBnk9lNDQ9Pbe0rwj8/AgVXi0ObalXPdWw+LNFs++uLjWqUTp31x4Y2s/pHrcmHlgDMKSH4yZnP9QHYL4odU2kE3zs2zzz2FmU70+VyRcqUB+7rl8smxN6OtiQJo1m/H3k4Hw7xiwl0b2Rb32MVpOR8nrLgTtzsZBV65yzCdUW+5f7tV75/XtuGWFDiF2g/b0hK+IFckSQaos1QOxLdDla3J7hnC9IiYv39ZdGvkHi/j6vE23QQyJ2emaAoyBAd1PrCJ86gza9pEcQ60usJRqCu8q7EpgQ4EqqI+nyYKMGX1e7ceLVKfkVjFDDIZhpoegdv8p01dTnn2csyjoeLS0EesnVD4l+loVnfjxpJevxeuRQ4aOW2znfzfs7jn6lGZQULge3lJitC51A2AuTa4psCdEqkZ5bJj9aC3MR08BNcSD8xe1ulHQrKK623+qakopm6I7e+PuTdS4O1JbCjHFtNxJL38k9m+8Z01lf/+HqWoRTAcq2+yt5JnmtjECwAKiBDs5CNwaBb+yFRvlIVVMrHnF/dh75wLw0oI3Cg8EmpQlpee5vY5bYYL/+wPOs0=
